version: '3.4'

services:
  work:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
    command: [ sleep, infinity ]
